### ISSUE TITLE
Use of LWRP provider ordering issues

### ISSUE THREAD

**Issue by dswebbthg** [target/pacemaker-cookbook#6]
One of the main "problems" with this cookbook that really isn't addressed in the documentation is the issue of ordering.

Lets say you have a 3 node cluster (node1[master],node2[slave],node3[slave]) that you want to control.  Before you can run any of the pacemaker::cluster_create scripts on node1, both node2/3 will have to have had the pacemaker::node_prepare recipes run against them.  Any deviation from this ordering will cause failures in the chef runs.  

Also, the various providers should really only be run against node1 in the cluster, as if you try to run them against node2/3 before the cluster creation is complete you will get errors in your chef run.

It would be ideal if there were information stored in some data bag or something that could be modified from within the recipes to inform the master that they've been successfully setup so the node_prepare or any primitive etc provider don't try and run until all "slave" nodes within the cluster have been setup.

**Comment by jmccann** [comment]
Please feel free to create a PR to make the documentation more clear.  We do currently call out the requirement to have run `recipe[pacemaker::node_prepare]` on all nodes before running `recipe[pacemaker::cluster_create]` on the last one @ https://github.com/target/pacemaker-cookbook#pacemakercluster_create

I will leave this open for now still however as being able to throw an error if `node_prepare` has not been ran on all nodes would be nice.  I'm not sure how doable that is without using Chef Search though which is something we are trying to avoid implementing.  Thoughts @tkilloren ?

**Comment by dswebbthg** [comment]
You are correct, it is there and I missed it (sorry, writing this up after playing with the cookbook last week).  Most of my issues came about because I was using the same recipe including_recipe the node prepare and cluster creation and not specifically telling the slave nodes not to run the providers.  I've worked around it by naming the first node in the nodes array as the "master" ala:

if node['fqdn'].eql?("#{node['pacemaker']['corosync']['nodes'].keys[0]}")
  include_recipe 'pacemaker::cluster_create'

  pacemaker_property 'stonith-enabled' do
    value  'false'
    action :set
  end
end

**Comment by jmccann** [comment]
Happy to hear you finally got it working.

For us we are using chef provisioning to create/manage our nodes and are modifying their run_list as it proceeds.  Something like:

```ruby
num_of_nodes = 3

# Prep nodes in parellel
machine_batch 'prep nodes for cluster create' do
  num_of_nodes.times do |i|
    nodeid = i + 1
    machine "mgmt#{nodeid}" do
      run_list ['recipe[pacemaker::node_prepare]']
      converge true
    end
  end
end

# Create cluster on last node
nodeid = num_of_nodes
machine "mgmt#{nodeid}" do
  run_list ['recipe[pacemaker::create_cluster]']
  converge true
end
```

Maybe I'll try adding both these examples to the README.  :wink:
